from dataclasses import dataclass
from typing import Literal


# ─── Type Aliases (Thesis Section 3.5.2) ──────────────────────────────────────

AppComplexity = Literal["LOW", "MEDIUM", "HIGH", "VERY_HIGH"]
ResourceType = Literal["EC2_SMALL", "EC2_MEDIUM", "EC2_LARGE", "EC2_XLARGE"]
DataSensitivity = Literal["PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED"]
IamPermissiveness = Literal["LEAST_PRIV", "MODERATE", "PERMISSIVE", "WILDCARD"]
EncryptionPosture = Literal["FULL", "PARTIAL", "TRANSIT_ONLY", "NONE"]
ComplianceScope = Literal["NONE", "SINGLE", "MULTIPLE", "CRITICAL"]
RecommendationPriority = Literal["CRITICAL", "IMPORTANT", "ADVISORY"]


@dataclass(frozen=True)
class MigrationAssessmentInput:
    """Migration parameters P as defined in the algorithm pseudocode."""

    project_name: str
    # Operational parameters
    data_volume_tb: float
    server_count: int
    app_complexity: AppComplexity
    migration_window_hrs: int
    # Financial parameters
    resource_type: ResourceType
    target_region: str
    egress_volume_tb: float
    capex_monthly_usd: float
    projected_users: int
    # Cybersecurity parameters
    data_sensitivity: DataSensitivity
    iam_permissiveness: IamPermissiveness
    encryption_posture: EncryptionPosture
    compliance_scope: ComplianceScope


@dataclass(frozen=True)
class RiskRecommendation:
    """Individual mitigation recommendation generated by the recommendation engine."""

    parameter: str
    dimension: str
    detail: str
    priority: RecommendationPriority
    score: float


@dataclass(frozen=True)
class RiskAssessmentResult:
    """Risk result R as defined in the algorithm pseudocode."""

    project_name: str
    composite_score: float
    operational_score: float
    financial_score: float
    cybersec_score: float
    risk_tier: Literal["LOW", "MEDIUM", "HIGH"]
    live_price_used: bool
    monthly_est_usd: float
    recommendations: list[RiskRecommendation]
